apiVersion: v2
name: opentelemetry
description: Red Hat build of OpenTelemetry operator installation and configuration
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: AutoShift
annotations:
  operator: opentelemetry-product
  category: observability
