{{- $defaultConfigs := (index $.Values "config" | default dict) }}
{{- range $clusterName, $cluster := $.Values.clusters }}
{{- $clusterConfig := (dict) }}
{{- $_ := (merge $clusterConfig (index $cluster "config" | default dict) $defaultConfigs) }}
  {{- if not (empty $clusterConfig) }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: "{{ printf "managed-cluster-config.%s" $clusterName }}"
  namespace: "{{ $.Values.policy_namespace }}" 
  labels:
    autoshift.io/cluster-configs: ""
data:
    config: '{{ $clusterConfig | toJson }}'
  {{- end }}
{{- end }}

{{- $clusterSets := (dict) }}
{{- $hubClusterSets := (index $.Values "hubClusterSets" | default dict) }}
{{- $managedClusterSets := (index $.Values "managedClusterSets" | default dict) }}
{{- range $clusterSetName, $clusterSet := (merge $clusterSets $hubClusterSets $managedClusterSets) }}
{{- $clusterSetConfig := (dict) }}
{{- $_ := (merge $clusterSetConfig (index $clusterSet "config" | default dict) $defaultConfigs) }}
  {{- if not (empty $clusterSetConfig) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "cluster-set-config.%s" $clusterSetName }}"
  namespace: "{{ $.Values.policy_namespace }}"
  labels:
    autoshift.io/cluster-set-configs: ""
data:
    config: '{{ $clusterSetConfig | toJson }}'
  {{- end }}
{{- end }}
---
