// Package resolver wraps the ACM go-template-utils library to resolve hub
// templates offline using synthetic ManagedClusterLabels.
package resolver

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/stolostron/go-template-utils/v7/pkg/templates"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	fakedynamic "k8s.io/client-go/dynamic/fake"
	fakeclientset "k8s.io/client-go/kubernetes/fake"
	fakediscovery "k8s.io/client-go/discovery/fake"
	sigsyaml "sigs.k8s.io/yaml"
)

// Resolver wraps the ACM TemplateResolver for offline hub template resolution.
type Resolver struct {
	inner *templates.TemplateResolver
}

// kindToResource converts a Kind to its lowercase plural resource name.
func kindToResource(kind string) string {
	lower := strings.ToLower(kind)
	if strings.HasSuffix(lower, "y") && len(lower) > 1 {
		if prev := lower[len(lower)-2]; !strings.ContainsRune("aeiou", rune(prev)) {
			return lower[:len(lower)-1] + "ies"
		}
	}
	if strings.HasSuffix(lower, "s") || strings.HasSuffix(lower, "x") ||
		strings.HasSuffix(lower, "z") || strings.HasSuffix(lower, "ch") ||
		strings.HasSuffix(lower, "sh") {
		return lower + "es"
	}
	return lower + "s"
}

// splitAPIVersion splits "group/version" → (group, version). Core "v1" → ("", "v1").
func splitAPIVersion(apiVersion string) (group, version string) {
	if idx := strings.Index(apiVersion, "/"); idx != -1 {
		return apiVersion[:idx], apiVersion[idx+1:]
	}
	return "", apiVersion
}

// buildRegistryFromResources derives the GVR→ListKind map and APIResourceList
// from a set of unstructured objects. Adding a YAML stub to testdata/ is
// sufficient to register that type — no code changes required.
func buildRegistryFromResources(resources []unstructured.Unstructured) (
	map[schema.GroupVersionResource]string,
	[]*metav1.APIResourceList,
) {
	type typeEntry struct {
		resource   string
		kind       string
		namespaced bool
	}
	seen := map[schema.GroupVersionResource]typeEntry{}

	for _, obj := range resources {
		apiVersion := obj.GetAPIVersion()
		kind := obj.GetKind()
		if apiVersion == "" || kind == "" {
			continue
		}
		grp, ver := splitAPIVersion(apiVersion)
		res := kindToResource(kind)
		gvr := schema.GroupVersionResource{Group: grp, Version: ver, Resource: res}
		if _, exists := seen[gvr]; !exists {
			seen[gvr] = typeEntry{
				resource:   res,
				kind:       kind,
				namespaced: obj.GetNamespace() != "",
			}
		}
	}

	listKinds := make(map[schema.GroupVersionResource]string, len(seen))
	byGV := map[string]*metav1.APIResourceList{}

	for gvr, e := range seen {
		listKinds[gvr] = e.kind + "List"
		gvKey := gvr.Group + "/" + gvr.Version
		if gvr.Group == "" {
			gvKey = gvr.Version
		}
		if byGV[gvKey] == nil {
			gv := gvr.Group + "/" + gvr.Version
			if gvr.Group == "" {
				gv = gvr.Version
			}
			byGV[gvKey] = &metav1.APIResourceList{GroupVersion: gv}
		}
		byGV[gvKey].APIResources = append(byGV[gvKey].APIResources, metav1.APIResource{
			Name:       e.resource,
			Kind:       e.kind,
			Namespaced: e.namespaced,
		})
	}

	lists := make([]*metav1.APIResourceList, 0, len(byGV))
	for _, l := range byGV {
		lists = append(lists, l)
	}
	return listKinds, lists
}

// NewResolver creates a Resolver with fake Kubernetes clients.
//
// localResources is a list of Kubernetes objects (e.g. ConfigMaps) that the
// resolver can return for `lookup`/`fromConfigMap` calls. Pass nil for
// hub-template-only resolution (Phase 1). Phase 2 will populate this with
// ConfigMaps generated by the cluster-config-maps chart.
func NewResolver(localResources []unstructured.Unstructured) (*Resolver, error) {
	listKinds, apiLists := buildRegistryFromResources(localResources)

	scheme := runtime.NewScheme()
	dynClient := fakedynamic.NewSimpleDynamicClientWithCustomListKinds(scheme, listKinds)
	fakeClientset := fakeclientset.NewSimpleClientset()

	if fakeDisc, ok := fakeClientset.Discovery().(*fakediscovery.FakeDiscovery); ok {
		fakeDisc.Resources = apiLists
	}

	tr, err := templates.NewResolverWithClients(
		dynClient,
		fakeClientset.Discovery(),
		templates.Config{
			StartDelim:            "{{hub",
			StopDelim:             "hub}}",
			AdditionalIndentation: 8,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("create template resolver: %w", err)
	}

	if len(localResources) > 0 {
		tr.WithLocalResources(localResources)
	}
	return &Resolver{inner: tr}, nil
}

// SetLocalResources updates the resolver's local resources. These are
// Kubernetes objects (typically ConfigMaps) that the resolver returns for
// `lookup`/`fromConfigMap` calls instead of hitting a real API server.
func (r *Resolver) SetLocalResources(resources []unstructured.Unstructured) {
	r.inner.WithLocalResources(resources)
}

// HubContext is the template context struct passed to the ACM resolver. The
// field names must be exported and match what hub templates reference:
// .ManagedClusterName, .ManagedClusterLabels.
type HubContext struct {
	ManagedClusterName   string
	ManagedClusterLabels map[string]string
}

// ResolvePolicyResult holds the outcome of resolving one multi-document YAML.
type ResolvePolicyResult struct {
	Resolved string   // the reassembled YAML (resolved where possible)
	Errors   []string // per-document resolution errors (non-fatal)
}

// ResolvePolicy takes raw multi-document YAML (from `helm template`), finds
// Policy documents, resolves their hub templates using the provided context,
// and returns the fully-resolved multi-document YAML.
//
// Non-Policy documents (Placement, PlacementBinding) are passed through
// unchanged. Spoke-side `{{ ... }}` templates are untouched because the
// resolver is configured with `{{hub`/`hub}}` delimiters.
//
// Resolution errors on individual Policy documents are collected as warnings
// rather than failing the entire chart. This allows charts with some
// `{{hub lookup ... hub}}` calls (which fail without real API resources) to
// still contribute their successfully-resolved Policy documents.
func (r *Resolver) ResolvePolicy(rawYAML string, ctx HubContext) ResolvePolicyResult {
	docs := splitYAMLDocuments(rawYAML)
	var resolved []string
	var errs []string

	for _, doc := range docs {
		doc = strings.TrimSpace(doc)
		if doc == "" {
			continue
		}

		// Parse to check the kind field.
		var obj map[string]interface{}
		if err := sigsyaml.Unmarshal([]byte(doc), &obj); err != nil {
			// If it doesn't parse as YAML (e.g. a comment block), pass through.
			resolved = append(resolved, doc)
			continue
		}

		kind, _ := obj["kind"].(string)
		if kind != "Policy" {
			// Placement, PlacementBinding, etc. — pass through unchanged.
			resolved = append(resolved, doc)
			continue
		}

		policyName, _ := nestedString(obj, "metadata", "name")

		// JSON-marshal the Policy for the resolver (it expects JSON input).
		jsonBytes, err := json.Marshal(obj)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: marshal to JSON: %v", policyName, err))
			resolved = append(resolved, doc) // pass through the original
			continue
		}

		result, err := r.inner.ResolveTemplate(jsonBytes, ctx, &templates.ResolveOptions{})
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: %v", policyName, err))
			resolved = append(resolved, doc) // pass through the original
			continue
		}

		// Convert resolved JSON back to YAML.
		resolvedYAML, err := sigsyaml.JSONToYAML(result.ResolvedJSON)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: convert to YAML: %v", policyName, err))
			resolved = append(resolved, doc)
			continue
		}

		resolved = append(resolved, string(resolvedYAML))
	}

	return ResolvePolicyResult{
		Resolved: strings.Join(resolved, "---\n"),
		Errors:   errs,
	}
}

// NewSpokeResolver creates a Resolver configured with spoke-side template
// delimiters ({{ / }}). This is used for the second rendering pass — after hub
// templates have been resolved, the remaining {{ }} expressions are evaluated
// on the managed cluster by config-policy-controller.
//
// Errors from spoke-side resolution are treated as warnings, not failures,
// because many spoke templates lookup real cluster resources (Infrastructure,
// DNS, etc.) that cannot be fully faked in CI.
func NewSpokeResolver(localResources []unstructured.Unstructured) (*Resolver, error) {
	listKinds, apiLists := buildRegistryFromResources(localResources)

	scheme := runtime.NewScheme()
	dynClient := fakedynamic.NewSimpleDynamicClientWithCustomListKinds(scheme, listKinds)
	fakeClientset := fakeclientset.NewSimpleClientset()

	if fakeDisc, ok := fakeClientset.Discovery().(*fakediscovery.FakeDiscovery); ok {
		fakeDisc.Resources = apiLists
	}

	tr, err := templates.NewResolverWithClients(
		dynClient,
		fakeClientset.Discovery(),
		templates.Config{
			StartDelim:            "{{",
			StopDelim:             "}}",
			AdditionalIndentation: 8,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("create spoke template resolver: %w", err)
	}

	if len(localResources) > 0 {
		tr.WithLocalResources(localResources)
	}
	return &Resolver{inner: tr}, nil
}

// ResolveSpokeTemplates resolves spoke-side {{ }} template expressions in
// multi-document YAML that has already had its hub templates resolved.
//
// Unlike ResolvePolicy (which only processes Policy documents), this method
// processes ALL document types since spoke templates can appear in any
// object inside a Policy's object-templates-raw.
//
// Resolution errors are returned as warnings in the result — many spoke
// templates lookup real cluster resources (Infrastructure, DNS) that can only
// be partially faked. A failure here does NOT indicate a broken policy; it
// just means CI couldn't fully exercise that code path.
func (r *Resolver) ResolveSpokeTemplates(rawYAML string, ctx ...HubContext) ResolvePolicyResult {
	docs := splitYAMLDocuments(rawYAML)
	var resolved []string
	var errs []string

	for _, doc := range docs {
		doc = strings.TrimSpace(doc)
		if doc == "" {
			continue
		}

		// Skip documents that have no spoke-side templates remaining.
		if !strings.Contains(doc, "{{") {
			resolved = append(resolved, doc)
			continue
		}

		var obj map[string]interface{}
		if err := sigsyaml.Unmarshal([]byte(doc), &obj); err != nil {
			resolved = append(resolved, doc)
			continue
		}

		kind, _ := obj["kind"].(string)
		name, _ := nestedString(obj, "metadata", "name")

		jsonBytes, err := json.Marshal(obj)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s %s: marshal: %v", kind, name, err))
			resolved = append(resolved, doc)
			continue
		}

		// Pass the cluster context so spoke templates that access .ManagedClusterLabels
		// (e.g., to derive the gitops namespace) resolve correctly.
		var spokeCtx interface{}
		if len(ctx) > 0 {
			spokeCtx = ctx[0]
		}
		result, err := r.inner.ResolveTemplate(jsonBytes, spokeCtx, &templates.ResolveOptions{})
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s %s: spoke resolve: %v", kind, name, err))
			resolved = append(resolved, doc)
			continue
		}

		resolvedYAML, err := sigsyaml.JSONToYAML(result.ResolvedJSON)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s %s: JSON→YAML: %v", kind, name, err))
			resolved = append(resolved, doc)
			continue
		}

		resolved = append(resolved, string(resolvedYAML))
	}

	return ResolvePolicyResult{
		Resolved: strings.Join(resolved, "---\n"),
		Errors:   errs,
	}
}

// nestedString extracts a string from a nested map path.
func nestedString(obj map[string]interface{}, keys ...string) (string, bool) {
	current := obj
	for i, k := range keys {
		v, ok := current[k]
		if !ok {
			return "", false
		}
		if i == len(keys)-1 {
			s, ok := v.(string)
			return s, ok
		}
		next, ok := v.(map[string]interface{})
		if !ok {
			return "", false
		}
		current = next
	}
	return "", false
}

// splitYAMLDocuments splits a multi-document YAML string on `---` boundaries.
func splitYAMLDocuments(raw string) []string {
	// Split on lines that are exactly "---" (possibly with trailing whitespace).
	var docs []string
	current := strings.Builder{}

	for _, line := range strings.Split(raw, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "---" {
			if current.Len() > 0 {
				docs = append(docs, current.String())
				current.Reset()
			}
			continue
		}
		current.WriteString(line)
		current.WriteString("\n")
	}
	if current.Len() > 0 {
		docs = append(docs, current.String())
	}

	return docs
}
