apiVersion: v2
name: servicemesh3operator
description: Red Hat OpenShift Service Mesh 3.x operator installation
type: application
version: 0.1.0
appVersion: "3.3.1"
maintainers:
  - name: AutoShift
annotations:
  operator: servicemeshoperator3
  category: networking
