{{- $policyNamespace := $.Values.policy_namespace }}
{{- $policyName := "policy-cluster-install-secrets" }}
{{- $placementName := (printf "placement-%s" $policyName) }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ $policyNamespace }}
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
{{- if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{- end }}
  dependencies:
    - name: policy-cluster-install-prereqs
      namespace: {{ $policyNamespace }}
      compliance: Compliant
      apiVersion: policy.open-cluster-management.io/v1
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $policyName }}
        spec:
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{ "{{-" }} $policyNamespace := "{{ "{{hub" }} (index .ManagedClusterLabels "{{ $.Values.autoshiftLabelPrefix | default "autoshift.io/" }}policy-namespace") | default "{{ $policyNamespace }}" {{ "hub}}" }}" {{ "}}" }}
            {{ "{{-" }} $configMaps := (lookup "v1" "ConfigMap" $policyNamespace "" "autoshift.io/rendered-config-map") | default dict {{ "}}" }}
            {{ "{{-" }} range $_, $cm := ($configMaps.items | default list) {{ "}}" }}
              {{ "{{-" }} $clusterName := (replace ".rendered-config" "" $cm.metadata.name) {{ "}}" }}
              {{ "{{-" }} $config := ($cm.data.config | fromYaml) {{ "}}" }}
              {{ "{{-" }} $ci := (index $config "clusterInstall" | default dict) {{ "}}" }}
              {{ "{{-" }} $platform := (index $ci "platform" | default "baremetal") {{ "}}" }}
              {{ "{{-" }} if eq (index $ci "createCluster" | default "") "true" {{ "}}" }}
                {{ "{{-" }} $secretSourceNs := (index $ci "secretSourceNamespace" | default "cluster-install-secrets") {{ "}}" }}
                {{ "{{-" }} if eq $platform "baremetal" {{ "}}" }}
                {{ "{{-" }} $defaultBmcCred := (index $ci "bmcCredentialRef" | default "default-bmc-cred") {{ "}}" }}
                {{ "{{-" }} $hosts := (index $config "hosts") {{ "}}" }}
                {{ "{{-" }} range $hostname, $host := $hosts {{ "}}" }}
                  {{ "{{-" }} $bmcRef := (index $host "bmcCredentialRef" | default dict) {{ "}}" }}
                  {{ "{{-" }} $bmcSecretName := (index $bmcRef "name" | default $defaultBmcCred) {{ "}}" }}
                  {{ "{{-" }} $bmcSecretNs := (index $bmcRef "namespace" | default $secretSourceNs) {{ "}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: Opaque
                metadata:
                  name: {{ "{{" }} $hostname {{ "}}" }}-bmc-cred
                  namespace: {{ "{{" }} $clusterName {{ "}}" }}
                data: '{{ "{{" }} copySecretData $bmcSecretNs $bmcSecretName | toLiteral {{ "}}" }}'
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} if eq $platform "baremetal" {{ "}}" }}
                {{ "{{-" }} $pullSecretRef := (index $ci "pullSecretRef" | default "default-pull-secret") {{ "}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: kubernetes.io/dockerconfigjson
                metadata:
                  name: {{ "{{" }} $clusterName {{ "}}" }}-pull-secret
                  namespace: {{ "{{" }} $clusterName {{ "}}" }}
                data: '{{ "{{" }} copySecretData $secretSourceNs $pullSecretRef | toLiteral {{ "}}" }}'
                {{ "{{-" }} end {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} end {{ "}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ $policyNamespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/cluster-install'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ $policyNamespace }}
placementRef:
  name: {{ $placementName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
