# Default values for servicemesh3-ambient
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
servicemesh3operator:
  # Istio ambient mode configuration
  istioNamespace: istio-system
  istioCNINamespace: istio-cni
  ztunnelNamespace: ztunnel
  istioVersion: v1.28-latest
  updateStrategy: InPlace
  tempoNamespace: tracing-system
  pilot:
    cpuRequest: "100m"
    memoryRequest: "256Mi"
  tempo:
    storageSize: 10Gi
