{{- if .Values.managedClusterSets }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acs-secured-cluster
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management, CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, CA-2 Security Assessments
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  dependencies:
    - name: policy-acs-sync-bundle
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-security-endpoints
        spec:
          remediationAction: enforce
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: SecuredCluster
                metadata:
                  namespace: {{ .Values.acs.namespace }}
                  name: stackrox-secured-cluster-services
                spec:
                  clusterName: '{{ "{{" }} fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec {{ "}}" }}'
                  auditLogs:
                    collection: Auto
                  centralEndpoint: '{{ "{{" }} fromSecret "{{ .Values.acs.namespace }}" "sensor-tls" "acs-host" | base64dec {{ "}}" }}'
                  {{ "{{hub-" }} if eq (index .ManagedClusterLabels "autoshift.io/acs-admission-control" | default "") "true" {{ "hub}}" }}
                  admissionControl:
                    listenOnCreates: true
                    listenOnEvents: true
                    listenOnUpdates: true
                  {{ "{{hub-" }} else {{ "hub}}" }}
                  admissionControl:
                    listenOnCreates: false
                    listenOnEvents: true
                    listenOnUpdates: false
                  {{ "{{hub-" }} end {{ "hub}}" }}
                  perNode:
                    collector:
                      collection: EBPF
                      imageFlavor: Regular
                    taintToleration: TolerateTaints
                  {{ "{{hub-" }} if eq (index .ManagedClusterLabels "autoshift.io/acs-monitoring" | default "{{ .Values.acs.monitoring }}") "true" {{ "hub}}" }}
                  monitoring:
                    openshift:
                      enabled: true
                  {{ "{{hub-" }} end {{ "hub}}" }}
                  {{ "{{hub-" }} if (index .ManagedClusterLabels "autoshift.io/acs-network-policies") {{ "hub}}" }}
                  network:
                    policies: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/acs-network-policies" {{ "hub}}" }}'
                  {{ "{{hub-" }} end {{ "hub}}" }}
                  {{ "{{hub-" }} if eq (index .ManagedClusterLabels "autoshift.io/acs-vm-scanning" | default "") "true" {{ "hub}}" }}
                  customize:
                    envVars:
                      - name: ROX_VIRTUAL_MACHINES
                        value: "true"
                  {{ "{{hub-" }} end {{ "hub}}" }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-security-endpoints-test
        spec:
          remediationAction: inform
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: SecuredCluster
                metadata:
                  namespace: {{ .Values.acs.namespace }}
                  name: stackrox-secured-cluster-services
                status:
                  conditions:
                    - status: 'True'
                      type: Deployed
                    - status: 'True'
                      type: Initialized
                    - status: 'False'
                      type: Irreconcilable
                    - status: 'False'
                      type: ProxyConfigFailed
                    - status: 'False'
                      type: ReleaseFailed
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-acs-secured-cluster-placement
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/acs'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-acs-secured-cluster-placement
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: policy-acs-secured-cluster-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-acs-secured-cluster
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{- end -}}