//go:build integration

package resolver

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/auto-shift/autoshiftv2/tools/internal/labels"
)

// repoRoot walks up from the package directory to find the repository root
// (identified by the presence of a `policies/` directory).
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "policies")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Skip("could not find repo root (no policies/ directory in any parent)")
		}
		dir = parent
	}
}

// TestPipeline_EndToEnd runs the full lint-labels pipeline against the real
// policies/ and autoshift/values/ directories. It mirrors what autoshift-ci
// does in CI.
//
// The test:
//   - fails if any chart fails helm template
//   - fails if any chart renders zero documents
//   - fails if any hub or spoke resolution error occurs
//   - fails if the label contract has Missing keys (consumed but not declared)
func TestPipeline_EndToEnd(t *testing.T) {
	root := repoRoot(t)

	policiesDir := filepath.Join(root, "policies")
	valuesDir := filepath.Join(root, "autoshift", "values")
	testdataDir := filepath.Join(root, "tools", "testdata")
	allowlistPath := filepath.Join(root, ".github", "label-lint-allowlist.yaml")

	// Verify required directories exist.
	for _, dir := range []string{policiesDir, valuesDir} {
		if _, err := os.Stat(dir); err != nil {
			t.Skipf("required directory missing, skipping e2e: %s", dir)
		}
	}

	// 1. Extract declared labels from example files.
	declared, err := labels.ExtractDeclaredFromTree(valuesDir, false)
	if err != nil {
		t.Fatalf("ExtractDeclaredFromTree: %v", err)
	}
	t.Logf("declared labels: %d", len(declared))

	// 2. Build synthetic labels and hub context.
	syntheticLabels := BuildSyntheticLabels(declared)
	ctx := HubContext{
		ManagedClusterName:   "lint-cluster",
		ManagedClusterLabels: syntheticLabels,
	}

	// 3. Extract hub config + cluster-install config from example files.
	configs, err := ExtractExampleConfigs(valuesDir)
	if err != nil {
		t.Fatalf("ExtractExampleConfigs: %v", err)
	}
	t.Logf("hub config keys: %d, cluster-install config keys: %d, bare labels: %d",
		len(configs.HubConfig), len(configs.ClusterInstallConfig), len(configs.BareLabels))

	// 4. Generate synthetic ConfigMaps and load testdata.
	syntheticCMs, err := GenerateSyntheticConfigMaps(configs, ctx.ManagedClusterName, "policies-autoshift")
	if err != nil {
		t.Fatalf("GenerateSyntheticConfigMaps: %v", err)
	}

	testResources, err := LoadTestResources(testdataDir)
	if err != nil {
		t.Fatalf("could not load testdata: %v", err)
	}

	seedResources := append(syntheticCMs, testResources...)

	// 5. Create hub and spoke resolvers.
	r, err := NewResolver(seedResources)
	if err != nil {
		t.Fatalf("NewResolver: %v", err)
	}
	spokeR, err := NewSpokeResolver(seedResources)
	if err != nil {
		t.Fatalf("NewSpokeResolver: %v", err)
	}

	// 6. Run the full pipeline.
	consumed, results, err := RunPipeline(policiesDir, ctx, r, spokeR, declared, configs, testdataDir)
	if err != nil {
		t.Fatalf("RunPipeline: %v", err)
	}

	// 7. Evaluate per-chart results + run output assertions.
	//
	// Hub resolution errors (ResolveOK=false) are hard failures: they mean a
	// hub template called fail or crashed, so the policy would never deploy to
	// any cluster. A new policy that guards a config section with fail will
	// automatically fail CI here if _example.yaml is missing that section.
	//
	// Spoke resolution errors are hard failures: all spoke templates must
	// resolve cleanly against testdata stubs in the test environment.
	// resolutionHint maps a resolution error string to a developer action hint.
	// The first matching substring wins.
	resolutionHint := func(errMsg string) string {
		switch {
		case strings.Contains(errMsg, "fromSecret") || strings.Contains(errMsg, "Secret"):
			return "hint: add a stub Secret to tools/testdata/ (see tools/testdata/acs-secrets.yaml for an example)"
		case strings.Contains(errMsg, "fromConfigMap") || strings.Contains(errMsg, "ConfigMap"):
			// Synthetic ConfigMaps are generated from _example.yaml config sections.
			// Real ConfigMaps that exist on the hub cluster must be stubbed in testdata.
			return "hint: if this ConfigMap is read from the hub cluster, add a stub to tools/testdata/;\n\t       if it is generated by a cluster-config chart, ensure the config section is populated in the\n\t       hubClusterSets.*.config block of autoshift/values/clustersets/_example.yaml"
		case strings.Contains(errMsg, "lookup"):
			return "hint: add a stub resource to tools/testdata/ so the hub lookup can resolve in CI"
		default:
			return "hint: check the template for undefined variables or missing _example.yaml values"
		}
	}

	resultsByPolicy := make(map[string]ChartResult, len(results))
	var helmFailures, emptyCharts, hubErrCharts, warnCharts, cleanCharts int
	for _, res := range results {
		resultsByPolicy[res.Policy] = res
		if res.Err != nil {
			t.Errorf("FAIL  %s: helm template failed: %v", res.Policy, res.Err)
			helmFailures++
			continue
		}
		if !res.ResolveOK {
			for _, w := range res.ResolveWarns {
				t.Errorf("FAIL  %s: hub resolution error: %s\n\t       %s", res.Policy, w, resolutionHint(w))
			}
			hubErrCharts++
			continue
		}
		if len(res.SpokeWarns) > 0 {
			for _, w := range res.SpokeWarns {
				t.Errorf("FAIL  %s: spoke resolution error: %s\n\t       %s", res.Policy, w, resolutionHint(w))
			}
			warnCharts++
		} else {
			cleanCharts++
		}
	}

	// 7b. Output assertions — verify config-driven branches actually rendered.
	// These catch cases where a config section is missing from example files:
	// the hub template silently skips the block and produces no output, but
	// no error is raised because the guard is `if (gt (len ...) 0)`.
	assertContains := func(policy, needle, reason string) {
		t.Helper()
		res, ok := resultsByPolicy[policy]
		if !ok {
			t.Errorf("output assertion: chart %s not found in results", policy)
			return
		}
		if res.Err != nil {
			return // already reported as a failure above
		}
		if !strings.Contains(res.ResolvedYAML, needle) {
			t.Errorf("output assertion FAIL  %s: expected %q in rendered output\n  reason: %s\n  hint: add this config section to the relevant _example*.yaml",
				policy, needle, reason)
		}
	}

	// nmstate: every distinct NNCP type the policy can generate must appear.
	// If any are missing, the corresponding config section is absent from
	// _example.yaml and that code path has never been tested.
	assertContains("stable/nmstate", "type: bond",
		"networking.interfaces must include a bond interface")
	assertContains("stable/nmstate", "type: vlan",
		"networking.interfaces must include a vlan interface")
	assertContains("stable/nmstate", "type: ovs-bridge",
		"networking.ovsBridges must be populated in hub example config")
	assertContains("stable/nmstate", "bridge-mappings",
		"networking.ovnMappings must be populated in hub example config")
	assertContains("stable/nmstate", "nmstate-host-",
		"hosts section with per-host networking overrides must be in cluster-install example")
	assertContains("stable/nmstate", "nodeSelector",
		"networking.nodeSelector must be set in hub example config")

	// nmstate routes: destination field must not be empty or "<no value>".
	// Catches the dest/destination key name mismatch between example and policy.
	// Go template renders a missing map key as "<no value>"; an empty string key
	// produces "destination: " (trailing space, becomes "destination:" after trim).
	if res, ok := resultsByPolicy["stable/nmstate"]; ok && res.Err == nil {
		for i, line := range strings.Split(res.ResolvedYAML, "\n") {
			trimmed := strings.TrimSpace(line)
			// Strip the YAML list marker so "- destination: <no value>" matches too.
			bare := strings.TrimPrefix(trimmed, "- ")
			if bare == "destination:" || bare == "destination: \"\"" || bare == "destination: ''" ||
				bare == "destination: <no value>" {
				t.Errorf("output assertion FAIL  stable/nmstate: line %d has empty/missing route destination\n  reason: route key in example uses 'dest' but policy reads 'destination'", i+1)
			}
		}
	}

	// disconnected-mirror: all four catalog source types must render when
	// config.disconnected is populated in the hub example.
	assertContains("stable/disconnected-mirror", "CatalogSource",
		"config.disconnected.catalogs must be populated in hub example config")
	assertContains("stable/disconnected-mirror", "ImageDigestMirrorSet",
		"config.disconnected.mirrorRegistry.mirrors must be populated in hub example config")

	// user-workload-monitoring: storage fields must be non-empty (UWM calls
	// fail if config.uwm is missing, but sub-fields degrade silently).
	assertContains("stable/user-workload-monitoring", "storage:",
		"config.uwm.prometheus.storage must be set in hub example config")

	t.Logf("\nACM resolution: %d clean, %d spoke errors, %d hub errors, %d helm failures (%d total)",
		cleanCharts, warnCharts, hubErrCharts, helmFailures, len(results))

	if helmFailures > 0 || emptyCharts > 0 || hubErrCharts > 0 || warnCharts > 0 {
		t.Errorf("%d chart(s) failed helm template, %d rendered empty, %d hub resolution errors, %d spoke resolution errors",
			helmFailures, emptyCharts, hubErrCharts, warnCharts)
	}

	// 8. Check the label contract.
	allow, err := labels.LoadAllowlist(allowlistPath)
	if err != nil {
		t.Fatalf("could not load allowlist: %v", err)
	}

	report := labels.BuildReport(consumed, declared, allow)

	// Write markdown report if LABEL_REPORT_OUTPUT is set (used by CI to
	// produce the uploadable artifact without a separate binary invocation).
	if reportPath := os.Getenv("LABEL_REPORT_OUTPUT"); reportPath != "" {
		f, err := os.Create(reportPath)
		if err != nil {
			t.Errorf("could not create report file %s: %v", reportPath, err)
		} else {
			labels.WriteMarkdown(f, report)
			f.Close()
			t.Logf("label contract report written to %s", reportPath)
		}
	}

	if len(report.Missing) > 0 {
		msgs := make([]string, 0, len(report.Missing))
		for _, entry := range report.Missing {
			policies := ""
			if entry.Consumed != nil {
				policies = strings.Join(entry.Consumed.Policies(), ", ")
			}
			msgs = append(msgs, fmt.Sprintf("  autoshift.io/%s (consumed by: %s)", entry.Key, policies))
		}
		t.Errorf("label contract violations — %d key(s) consumed by policy templates but missing from all _example*.yaml files:\n%s\n\n"+
			"  fix: add each missing label under a `labels:` block in\n"+
			"       autoshift/values/clustersets/_example.yaml (for hub/cluster-set labels) or\n"+
			"       autoshift/values/clusters/_example.yaml (for per-cluster labels)\n"+
			"  once added, re-run: go test -tags integration -run TestPipeline_EndToEnd ./tools/internal/resolver/...",
			len(report.Missing), strings.Join(msgs, "\n"))
	}

	t.Logf("label contract: %d OK, %d missing, %d orphaned",
		len(report.OK), len(report.Missing), len(report.Orphaned))
}

